spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_easylife
    username: root
    password: 123123
  http:
   multipart:
     location: G:/EasyLife/public/
     max-request-size: 20Mb
     max-file-size: 5Mb
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${spring.http.multipart.location}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
